name: deploy

on:
  workflow_dispatch: null
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge,defaults
        channel-priority: strict
        auto-activate-base: true
        python-version: 3.9

    - name: update JSON payload
      shell: bash -l {0}
      run: |
        python scripts/all_json.py outputs/ site/feedstock-outputs.json

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
